deepseek_api: "sk-11efea697f564cff8c16d9cfbd1ae4ce"
gemini_api: "AIzaSyD3EapiXTRKwYh94H-z0ugBIdFdNJ0TCCY"
file_path: "./data/result_task_all.xlsx"
save_path: "./data/Prob_WITH_RA"
target_problem_col: "Problem_with_redundant_assumption"
