deepseek_api: "sk-dd63f7052da3415ba905d650b50f89aa"
gemini_api: "AIzaSyDyiHKgl6OClxeAZ0hDN-otUlc97EdazoY"
file_path: "./data/donedatasetdanhsogiathietplusredundant_v2.xlsx"
save_path: "./data/Prob_WITHOUT_RA_from_100_v2"
target_problem_col: "Original_Problem_with_numerical_assumption" # "Problem_with_redundant_assumption"